
import json
import os
import uuid
from pathlib import Path
from datetime import datetime
from pydantic import BaseModel
from typing import Optional, List

# Define the models locally to avoid import issues for isolation
class Message(BaseModel):
    id: str
    content: str
    sender: str
    timestamp: datetime
    session_id: Optional[str] = None
    status: str = "sent"

def test_message_model():
    print("Testing Message model...")
    m = Message(
        id="123",
        content="test",
        sender="agent",
        timestamp=datetime.now(),
        status="pending"
    )
    assert m.status == "pending"
    print("SUCCESS: Message model supports status field.")

def test_resident_memory_update():
    print("\nTesting ResidentMemory status update...")
    from app.services.resident_link import ResidentMemory
    
    # Setup mock data dir
    data_dir = Path("./test_data")
    data_dir.mkdir(exist_ok=True)
    
    # Mock ResidentMemory for testing status update
    # We can use the actual ResidentMemory class but pointed to test_data
    memory = ResidentMemory("./test_data")
    
    msg_id = str(uuid.uuid4())
    session_id = "peer_1"
    content = "Hello status test"
    
    # 1. Log as pending
    memory.log_interaction("agent", content, session_id=session_id, status="pending")
    
    # Verify it was logged as pending
    log_file = data_dir / "chat.jsonl"
    with open(log_file, 'r') as f:
        line = f.readline()
        data = json.loads(line)
        # The ID in the log is generated by log_interaction, let's find it
        logged_id = data["id"]
        assert data["status"] == "pending"
        print(f"SUCCESS: Logged as 'pending' (ID: {logged_id})")
    
    # 2. Update to sent
    memory.update_message_status(logged_id, "sent")
    
    # Verify update
    with open(log_file, 'r') as f:
        line = f.readline()
        data = json.loads(line)
        assert data["status"] == "sent"
        print("SUCCESS: Log entry updated to 'sent'")
        
    # Cleanup
    os.remove(log_file)
    data_dir.rmdir()

if __name__ == "__main__":
    test_message_model()
    try:
        test_resident_memory_update()
    except Exception as e:
        print(f"ResidentMemory test failed: {e}")
        import traceback
        traceback.print_exc()
