import argparse
import os
import json
import logging
from datetime import datetime
from pathlib import Path
from watcher_service import WatcherService, _load_env_file

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def generate_markdown_brief(topic, papers, output_path):
    """
    Generates a professional Markdown brief for the identified papers.
    """
    now = datetime.now().strftime('%Y-%m-%d %H:%M')
    
    md = f"# 🔬 Literature Briefing: {topic}\n\n"
    md += f"**Generaton Date**: {now}\n"
    md += f"**New Papers Identified**: {len(papers)}\n\n"
    
    if not papers:
        md += "No new papers found in the specified interval.\n"
    else:
        md += "## 📈 Key Findings & New Publications\n\n"
        for i, p in enumerate(papers, 1):
            md += f"### {i}. {p['title']}\n"
            md += f"- **Authors**: {p['authors']}\n"
            md += f"- **Date**: {p['publication_date']} | **Source**: {p['source']}\n"
            md += f"- **Citations**: {p['citations']}\n"
            if p['doi']:
                md += f"- **DOI**: [{p['doi']}](https://doi.org/{p['doi']})\n"
            
            if p['abstract']:
                # Shorten abstract for briefing
                abstract_preview = p['abstract'][:500] + "..." if len(p['abstract']) > 500 else p['abstract']
                md += f"\n**Summary**: {abstract_preview}\n"
            
            md += f"\n---\n"
            
    md += "\n\n*This briefing was automatically generated by BitPoliteia Literature Watcher.*项目根目录下 `backend/data/watcher_history.db` 已记录以上文献，防止重复提醒。\n"
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(md)
    
    return md

def main():
    parser = argparse.ArgumentParser(description="Literature Watcher Briefing Generator")
    parser.add_argument("--topic", required=True, help="Keyword or topic to monitor")
    parser.add_argument("--interval", type=int, default=7, help="Lookback interval in days")
    parser.add_argument("--output", help="Specific output file path")
    parser.add_argument("--no-save", action="store_true", help="Don't save to history (dry run)")
    
    args = parser.parse_args()
    
    # Load env vars
    _load_env_file()
    
    service = WatcherService()
    logger.info(f"Starting scheduled update for topic: {args.topic}")
    
    new_papers = service.get_incremental_papers(args.topic, interval_days=args.interval)
    
    if args.output:
        out_path = Path(args.output)
    else:
        # Default output dir: backend/data/briefs/
        base_dir = Path(__file__).resolve().parent.parent.parent.parent
        out_dir = base_dir / "data" / "briefs"
        out_dir.mkdir(parents=True, exist_ok=True)
        filename = f"brief_{args.topic.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d')}.md"
        out_path = out_dir / filename
        
    generate_markdown_brief(args.topic, new_papers, out_path)
    logger.info(f"Briefing generated at: {out_path}")
    
    # Update history
    if not args.no_save and new_papers:
        service.save_to_history(new_papers)
        logger.info(f"Added {len(new_papers)} papers to history.")
    elif args.no_save:
        logger.info("Dry run: not updating history.")

if __name__ == "__main__":
    main()
